version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # Command to run the application, overriding the CMD in Dockerfile for development
    # This allows for live reloading if uvicorn is configured for it
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
